<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="doris" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass_riser" value="3" /> <!-- arbitrary value for mass -->
  
  <xacro:property name="riser_x" value="0.04" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="riser_y" value="0.04" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height_riser" value="0.925" /> <!-- Link 1 -->
  
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find doris_description)/urdf/doris.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find doris_description)/urdf/materials.xacro" />

  <!--
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="riser"/>
  </joint>
  -->



  <!-- right front wheel -->
	<link name="right_front_wheel">
		<inertial>
			<mass value="1.5"/>
			<origin xyz="0.0 -0.04 0.00"/>
			<inertia ixx="0.0051" ixy="0.0" ixz="0.0"
				 iyy="0.0051" iyz="0.0"
				 izz="0.009"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0.0 -0.04 0.00" rpy="1.5707 1.5707 0"/>
			<geometry>
				<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
			</geometry>			
		</visual>
		<collision>
			<origin xyz="0.0 -0.04 0.00" rpy="1.5707 1.5707 0"/>
				<geometry>
					<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
				</geometry>
		</collision>
	</link>

  <joint name="right_front_wheel_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="0.13 -0.17 0.11" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>


  <!-- left front wheel -->
	<link name="left_front_wheel">
		<inertial>
			<mass value="1.5"/>
			<origin xyz="0.0 0.04 0.00"/>
			<inertia ixx="0.0051" ixy="0.0" ixz="0.0"
				 iyy="0.0051" iyz="0.0"
				 izz="0.009"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0.0 0.04 0.00" rpy="1.5707 1.5707 0"/>
			<geometry>
				<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
			</geometry>			
		</visual>
		<collision>
			<origin xyz="0.0 0.04 0.00" rpy="1.5707 1.5707 0"/>
				<geometry>
					<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
				</geometry>
		</collision>
	</link>

  <joint name="left_front_wheel_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="0.13 0.17 0.11" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  
  
  <link name="left_back_wheel">
		<inertial>
			<mass value="1.5"/>
			<origin xyz="0.0 0.04 0.00"/>
			<inertia ixx="0.0051" ixy="0.0" ixz="0.0"
				 iyy="0.0051" iyz="0.0"
				 izz="0.009"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0.0 0.04 0.00" rpy="1.5707 1.5707 0"/>
			<geometry>
				<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
			</geometry>			
		</visual>
		<collision>
			<origin xyz="0.0 0.04 0.00" rpy="1.5707 1.5707 0"/>
				<geometry>
					<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
				</geometry>
		</collision>
	</link>

  <joint name="left_back_wheel_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin xyz="-0.13 0.17 0.11" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  
  
  <link name="right_back_wheel">
		<inertial>
			<mass value="1.5"/>
			<origin xyz="0.0 -0.04 0.00"/>
			<inertia ixx="0.0051" ixy="0.0" ixz="0.0"
				 iyy="0.0051" iyz="0.0"
				 izz="0.009"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0.0 -0.04 0.00" rpy="1.5707 1.5707 0"/>
			<geometry>
				<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
			</geometry>			
		</visual>
		<collision>
			<origin xyz="0.0 -0.04 0.00" rpy="1.5707 1.5707 0"/>
				<geometry>
					<mesh filename="package://doris_description/urdf/meshes/wheel.dae"/>
				</geometry>
		</collision>
	</link>

  <joint name="right_back_wheel_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin xyz="-0.13 -0.17 0.11" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  -->
  <!-- Chassis -->
	<link name="base_link">
		<inertial>
			<mass value="14.0"/>
			<origin xyz="0 0 0.18"/>
			<inertia ixx="0.147" ixy="0.0" ixz="0.0"
				 iyy="0.3349" iyz="0.0"
				 izz="0.3978"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0 0 0.18" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://doris_description/urdf/meshes/chassis.dae"/>
			</geometry>			
		</visual>
		<collision>
			<origin xyz="0 0 0.18" rpy="0 0 0"/>
      <geometry>
			  <box size="0.501 0.3 0.19"/>
      </geometry>
		</collision>
	</link>

  <joint name="pioneer_manipulator_joint" type="fixed">
    <parent link="base_link"/>
    <child link="riser"/>
    <origin xyz="0.0 0.0 0.27" rpy="0 0 0"/>    
  </joint>

   <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.2 0 0.3" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  
  

  <transmission name="tranrightfrontwheel">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_front_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorrightfrontwheeljoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>75.0676691729</mechanicalReduction>
    </actuator>
  </transmission>  

  <transmission name="tranleftfrontwheel">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_front_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorleftfrontwheeljoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>75.0676691729</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tranleftbackwheel">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_back_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorleftbackwheeljoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>75.0676691729</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tranrightbackwheel">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_back_wheel_hinge">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorrightbackwheeljoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>75.0676691729</mechanicalReduction>
    </actuator>
  </transmission>

  
  

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height_riser+0.02}" rpy="0 0 0"/>
    <parent link="riser"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.04 0.04 0.04"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>





  <!-- Manipulator -->

  <!-- Base Link -->
  <link name="riser">
    <collision>
      <origin xyz="0 0 ${height_riser/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${riser_x} ${riser_y} ${height_riser}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height_riser/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${riser_x} ${riser_y} ${height_riser}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height_riser/2}" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia
	  ixx="${mass_riser / 12.0 * (riser_y*riser_y + height_riser*height_riser)}" ixy="0.0" ixz="0.0"
	  iyy="${mass_riser / 12.0 * (height_riser*height_riser + riser_x*riser_x)}" iyz="0.0"
	  izz="${mass_riser / 12.0 * (riser_x*riser_x + riser_y*riser_y)}"/>
    </inertial>
  </link>
  

  <joint name="riser_shoulder_joint" type="fixed">
    <parent link="riser"/>
    <child link="shoulder"/>
    <origin xyz="0.02 0.0 0.665" rpy="0 0 0"/>    
  </joint>
  <!-- Base Link -->
  <link name="shoulder">
    <collision>
      <origin xyz="0.035 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.07 0.05 0.13"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0.025 -0.065" rpy="0 0 -1.5707"/>
      <geometry>
	      <!--<box size="${shoulder_x} ${shoulder_y} ${height_shoulder}"/> -->
        <mesh filename="package://doris_description/urdf/meshes/shoulderyaw.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.035 0 0" rpy="0 0 0"/>
      <mass value="0.085"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="shoulder_yaw_joint" type="revolute">
    <parent link="shoulder"/>
    <child link="shoulder_pitch"/>
    <origin xyz="0.065 0.0 0.065" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="6.5" effort="1000" lower="${-pi*0.5}" upper="${pi*0.5}" />
    <dynamics damping="0.1" friction="0.0" />
  </joint>
  
  <link name="shoulder_pitch">
    <collision>
      <origin xyz="0.01 0 -0.04" rpy="0 0 0"/>
      <geometry>
	      <box size="0.08 0.05 0.17"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.12 -0.08 0.05" rpy="3.1415 0 1.9"/>
      <geometry>
	      <mesh filename="package://doris_description/urdf/meshes/shoulderpitch.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.111"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  
  <joint name="shoulder_pitch_joint_down" type="continuous">
    <parent link="shoulder_pitch"/>
    <child link="shoulder_elbow_link_down"/>    
    <origin xyz="-0.015 0.0 -0.095" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="shoulder_elbow_link_down">
    <collision>
      <origin xyz="0.1275 0 -0.03" rpy="0 0 0"/>
      <geometry>
	      <box size="0.255 0.10 0.06"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.015 0.045 -0.085" rpy="0.04 0 -1.5707"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/shoulder_elbow.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  



  <joint name="shoulder_pitch_joint_up" type="continuous">
    <parent link="shoulder_pitch"/>
    <child link="shoulder_elbow_link_up"/>    
    <origin xyz="-0.015 0.0 -0.04" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="shoulder_elbow_link_up">
    <collision>
      <origin xyz="0.1275 0 0.03" rpy="0 0 0"/>
      <geometry>
	      <box size="0.255 0.10 0.06"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.015 -0.04 0.085" rpy="3.18 0 1.5707"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/shoulder_elbow.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  



  
  <joint name="shoulder_elbow_joint" type="continuous">
    <parent link="shoulder_elbow_link_up"/>
    <child link="elbow"/>    
    <origin xyz="0.25 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint> 
  
  <link name="elbow">
    <collision>
      <origin xyz="0.06 0 -0.03" rpy="0 0 0"/>
      <geometry>
	      <box size="0.1275 0.04 0.12"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.13 -0.04 -0.14" rpy="0 0 1.5707"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/elbow.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  
  <joint name="elbow_pitch_joint_up" type="continuous">
    <parent link="elbow"/>
    <child link="elbow_wrist_link_up"/>    
    <origin xyz="0.11 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="elbow_wrist_link_up">
    <collision>
      <origin xyz="0.10 0 0.03" rpy="0 0 0"/>
      <geometry>
	      <box size="0.20 0.10 0.06"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.03 -0.0425 0.075" rpy="3.08 0 1.5707"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/elbow_wrist.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="elbow_pitch_joint_down" type="continuous">
    <parent link="elbow"/>
    <child link="elbow_wrist_link_down"/>    
    <origin xyz="0.11 0.0 -0.055" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="elbow_wrist_link_down">
    <collision>
      <origin xyz="0.10 0 -0.03" rpy="0 0 0"/>
      <geometry>
	      <box size="0.20 0.10 0.06"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.24 -0.0425 -0.07" rpy="-0.06 0 1.5707"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/elbow_wrist.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="hearth_joint" type="continuous">
    <parent link="elbow_wrist_link_up"/>
    <child link="hearth_link"/>    
    <origin xyz="0.21 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="hearth_link">
    
    <visual>
      <origin xyz="-0.015 0.0 -0.067" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/hearth_gripper.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_pitch_joint" type="continuous">
    <parent link="hearth_link"/>
    <child link="gripper_pitch"/>    
    <origin xyz="0.02 0.0 -0.02" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="gripper_pitch">
    <collision>
      <origin xyz="-0.0075 0 -0.025" rpy="0 0 0"/>
      <geometry>
	      <box size="0.06 0.04 0.12"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.0475 0.0 -0.075" rpy="1.5707 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/base_gripper.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_yaw_joint" type="continuous">
    <parent link="gripper_pitch"/>
    <child link="gripper_yaw"/>    
    <origin xyz="0.0025 0.0 -0.035" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="gripper_yaw">
    <collision>
      <origin xyz="0.05 0 0.04" rpy="0 0 0"/>
      <geometry>
	      <box size="0.08 0.06 0.08"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.01 0.0 -0.0" rpy="1.5707 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/gripper_yaw.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>


  <joint name="gripper_roll_joint" type="continuous">
    <parent link="gripper_yaw"/>
    <child link="gripper_roll"/>    
    <origin xyz="0.09 0.0 0.045" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="gripper_roll">
    <collision>
      <origin xyz="0.03 0 0.0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.06 0.1 0.04"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.0 0.0 -0.015" rpy="1.5707 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/gripper_roll.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>


  <joint name="gripper_right_joint" type="continuous">
    <parent link="gripper_roll"/>
    <child link="gripper_right"/>    
    <origin xyz="0.045 -0.0225 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="gripper_right">
    <collision>
      <origin xyz="0.075 -0.015 0.0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.12 0.03 0.04"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-0.0175 -0.0025 -0.0225" rpy="1.5707 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/gripper_right.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="gripper_left_joint" type="continuous">
    <parent link="gripper_roll"/>
    <child link="gripper_left"/>    
    <origin xyz="0.045 0.0225 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/> 
  </joint>

  <link name="gripper_left">
    <collision>
      <origin xyz="0.075 0.015 0.0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.12 0.03 0.04"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0.0025 -0.0225" rpy="1.5707 0 0"/>
      <geometry>
        <mesh filename="package://doris_description/urdf/meshes/gripper_left.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.11"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
    
  <transmission name="transhoulderyaw">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_yaw_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorshoulderyawjoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="transhoulderpitchdown">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_pitch_joint_down">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorshoulderpitchjointdown">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="transhoulderpitchup">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_pitch_joint_up">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorshoulderpitchjointup">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="transhoulderelbow">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_elbow_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorshoulderelbowjoint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tranelbowpitchup">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow_pitch_joint_up">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorelbowpitchjointup">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tranelbowpitchdown">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elbow_pitch_joint_down">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorelbowpitchjointdown">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trangripperhearth">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="hearth_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperhearth">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trangripperpitch">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_pitch_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperpitch">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
 
  <transmission name="trangripperyaw">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_yaw_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperyaw">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trangripperroll">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_roll_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperroll">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trangripperright">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_right_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperright">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trangripperleft">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_left_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motorgripperleft">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
</robot>

<!--

 
rostopic pub -1 /doris/gripper_right_joint_position_controller/command std_msgs/Float64 "data: 0.0"
rostopic pub -1 /doris/gripper_left_joint_position_controller/command std_msgs/Float64 "data: 0.0"

rostopic pub -1 /doris/shoulder_yaw_joint_position_controller/command std_msgs/Float64 "data: 0"
rostopic pub -1 /doris/shoulder_pitch_joint_up_position_controller/command std_msgs/Float64 "data: 0."
rostopic pub -1 /doris/shoulder_elbow_joint_up_position_controller/command std_msgs/Float64 "data: 0"
rostopic pub -1 /doris/elbow_pitch_joint_up_position_controller/command std_msgs/Float64 "data: 0."




rosrun rqt_image_view rqt_image_view
-->