butia_manipulation:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  right_front_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  left_front_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_wheel_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # manipulator
  shoulder_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  shoulder_pitch_joint_down_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pitch_joint_down
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  shoulder_pitch_joint_up_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pitch_joint_up
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shoulder_elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  elbow_pitch_joint_up_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_pitch_joint_up
    pid: {p: 100.0, i: 0.01, d: 10.0}
 
  elbow_pitch_joint_down_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_pitch_joint_down
    pid: {p: 100.0, i: 0.01, d: 10.0}

  hearth_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hearth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  gripper_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  gripper_yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  gripper_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  gripper_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  gripper_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}